/* SPDX-License-Identifier: Apache-2.0 */

/**
 * End-to-end PCM -> TFLite input pipeline (pure C).
 * Pair with model_config.h generated by Sound Model Studio export.
 */

#ifndef SOUND_PIPELINE_H
#define SOUND_PIPELINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

#include "sound_features.h"

typedef struct {
    sf_config_t feature;
    int input_frames;
    int input_mels;
    float norm_mean;
    float norm_std;
    float input_scale;
    int input_zero_point;
    float output_scale;
    int output_zero_point;
    /* Display label count (includes synthetic "other" for open-set). */
    int num_labels;
    /* Target classes; 0 = legacy full-softmax over num_labels. */
    int num_target_labels;
    /* TFLite output length (emb_dim for prototype, or num targets / labels). */
    int output_dim;
    /* Reject as other when max(score) is below this (sigmoid or cosine). */
    float is_target_threshold;
    /* Prototype open-set: L2 class means, row-major [num_prototypes * emb_dim]. */
    int emb_dim;
    int num_prototypes;
    const float *prototypes;
} sound_model_params_t;

typedef struct {
    sound_model_params_t params;
    sf_context_t feature_ctx;
    float *mel_buf;
    float *model_float_buf;
    int8_t *model_int8_buf;
} sound_pipeline_t;

/** Bytes required for mel + float + int8 model buffers. */
size_t sound_pipeline_buffer_bytes(const sound_model_params_t *params);

/**
 * Initialize pipeline using an external memory block for feature context + tensors.
 * feature_mem must be at least sf_context_buffer_bytes + sound_pipeline_buffer_bytes.
 */
int sound_pipeline_init(
    sound_pipeline_t *pipe,
    const sound_model_params_t *params,
    void *feature_mem,
    size_t feature_mem_bytes
);

void sound_pipeline_deinit(sound_pipeline_t *pipe);

/** PCM float32 mono -> quantized int8 model input. */
int sound_pipeline_pcm_float_to_input(
    sound_pipeline_t *pipe,
    const float *pcm,
    int n_pcm,
    int8_t *tflite_input,
    int tflite_input_bytes
);

/** PCM int16 mono -> quantized int8 model input. */
int sound_pipeline_pcm16_to_input(
    sound_pipeline_t *pipe,
    const int16_t *pcm,
    int n_pcm,
    int8_t *tflite_input,
    int tflite_input_bytes
);

/** Decode int8 TFLite output to class index and confidence.

 * Legacy closed-set: argmax over num_labels softmax probs.
 * Prototype open-set (prototypes set and output_dim == emb_dim):
 *   cosine sim to each prototype; if max(sim) < threshold -> other else argmax.
 * Sigmoid-ovr open-set (num_target_labels > 0 and output_dim == num_target_labels):
 *   if max(sigmoid) < threshold -> other else argmax.
 * Legacy dual-head (output_dim == num_target_labels+1): last is P(is_target).
 */
int sound_pipeline_decode_output(
    const sound_model_params_t *params,
    const int8_t *tflite_output,
    int tflite_output_bytes,
    int *label_index,
    float *confidence
);

#ifdef __cplusplus
}
#endif

#endif /* SOUND_PIPELINE_H */
